### ISSUE TITLE
ファイル形式を指定してダウンロードは可能ですか？

### ISSUE THREAD

**Issue by nsho-46** [strd3983/bilibili_downloader#13]
H265フォーマットでダウンロードされるファイルが有り、H264としてダウンロードしたい場合の手段はありますでしょうか？

**Comment by strd3983** [comment]
現状はないですね...ダウンロード後に変換してもらう必要があります。
ソースコード上では以下の部分でH265（AV1やHEVC）を優先しているので、Pythonができるのであれば改変してみれば行けると思います。
https://github.com/strd3983/bilibili_downloader/blob/64ef033674538ea5fcf603882ff1dbe6d1f2d305/bilibili_downloader.py#L349-L351

必要があれば設定ファイル等で指定できるようにしておきます。

**Comment by nsho-46** [comment]
承知いたしました。　Pythonは触れないので大人しく変換することにします。ありがとうございます。

**Comment by strd3983** [comment]
```bash
ffmpeg -i input.mp4 -map 0 -c:v libx264 -crf 18 -c:a copy output.mp4
```
とかで行けると思います．
時間があればsettingファイルで指定できるようにするので、issueは開けておいてください。

**Comment by strd3983** [comment]
長らくお待たせしましたが、次のリリースで対応します。
