### ISSUE TITLE
変換処理後の 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by 7min3AO7wug** [strd3983/bilibili_downloader#14]
v2024.01.05 にて、変換処理後に下記のようなエラーが発生しておりました。
変換したファイルは再生できておりました。

エラー内容をご確認頂ければ幸いです。

-----
[M] ファイルを変換中...
[M] 5秒待機中...
[E] 'NoneType' object is not subscriptable
###--------------------------------------###
[M] マイリスid: ml[数字] または動画id: BV[文字列] を入力. 終了する場合はexitを入力.

**Comment by strd3983** [comment]
現状こちらで再現できないので分からないですね...
恐らく動画リスト内にダウンロードできない動画が含まれているような気がしますが...
可能であれば次の情報を教えていただけますか？

- OSは何か
- アカウントにログインした状態か
- ダウンロードしたいマイリスidか動画id
- 他のリストや動画でも同様にエラーが出るか

**Comment by 7min3AO7wug** [comment]
ご確認いただき、有難うございます。
こちらで確認した内容は以下の通りです。

１．Windows11 23H2 ver.22631.3296
２．Firefox 123.0.1 (64 ビット) にてログインした状態
３．動画ID: BV1zm411R76E
  画質をmp3から1080pまで試しましたがいずれのパラメタでも、ファイル変換が完了し5秒待機後に同様のエラー発生
４．他の動画のなかで、エラーが発生した動画と同じ位の尺の動画で実施しましたがエラーは出ませんでした。
　また短い尺の動画でもエラーは発生しませんでした。

**Comment by strd3983** [comment]
遅くなりましたが解析と修正が完了しました。
同idの動画には2ページ目があり、その動画には音声がないために空のデータを参照したエラーのようでした。
一応確認のため、以下のファイルを試してもらえますか？
[bilibili_downloader.zip](https://github.com/strd3983/bilibili_downloader/files/14653153/bilibili_downloader.zip)

**Comment by 7min3AO7wug** [comment]
テストverのご提供、有難うございます。
エラーが発生した動画をテストverで実行したところ、エラーなく2ページ目の音声なしの動画ファイルがダウンロードされました。


上記とは別件にはなりますが、テストverの正常系をテストするため
動画ID：BV1Ws411x7iE
を画質360p でダウンロードしたところ、2ページ目の画質が720pでダウンロードされてしまいました。
・対象の動画はブラウザで、1Pおよび2Pいずれも360pを選択可能でした。
・上記動作は、release v2024.01.05 でも発生しました。

※テストverの標準出力は以下の通りでした。
---
[M] マイリスid: ml[数字] または動画id: BV[文字列] を入力. 終了する場合はexitを入力.
 >> BV1Ws411x7iE
[M] マイリストのタイトル: Individual
[M] ダウンロードする動画数: 1
[M] ダウンロードする画質: 1080p60 720p60 1080p+ 1080p 720p 480p 360p mp3
[M] mp3を指定すると音声ファイルのみがダウンロード
>> 360p
###----------------| 1/1 |----------------###
[M] ダウンロード画質: 360p
[M] 少年Pi - pi,mc,恐锤P1_x264
[M] hev1: 100%|██████████| 90.9M/90.9M [01:52<00:00, 806kB/s]
[M] mp4a: 100%|██████████| 38.1M/38.1M [00:00<00:00, 103MB/s]
[M] ファイルを変換中...
[M] 5秒待機中...
[W] 720p60や1080pは一般会員, 1080p60以上は有料会員のログインが必要です
[W] (一部動画は自動的にこの警告が表示されます. その場合は無視してください.)
[M] ダウンロード画質: 720p
[M] 少年Pi - pi,mc,恐锤P2_x264
[M] avc1: 100%|██████████| 297M/297M [03:51<00:00, 1.28MB/s]
[M] mp4a: 100%|██████████| 33.3M/33.3M [00:00<00:00, 96.3MB/s]
[M] ファイルを変換中...
[M] 5秒待機中...
###--------------------------------------###
[M] マイリスid: ml[数字] または動画id: BV[文字列] を入力. 終了する場合はexitを入力.

**Comment by strd3983** [comment]
検証ありがとうございます。
気づいていませんでしたが、どうやらコーデック選択でミスってたみたいですね。
こちらでどうでしょうか？
[bilibili_downloader.zip](https://github.com/strd3983/bilibili_downloader/files/14662045/bilibili_downloader.zip)

**Comment by 7min3AO7wug** [comment]
早々のご対応、有難うございます。
新しいテストverにて、指定した画質で各ページの動画がダウンロードされました。

※以下、標準出力の結果です。
[M] マイリスid: ml[数字] または動画id: BV[文字列] を入力. 終了する場合はexitを入力.
 \>\> BV1Ws411x7iE
[M] マイリストのタイトル: Individual
[M] ダウンロードする動画数: 1
[M] ダウンロードする画質: 1080p60 720p60 1080p+ 1080p 720p 480p 360p mp3
[M] mp3を指定すると音声ファイルのみがダウンロード
\>\> 360p
###----------------| 1/1 |----------------###
[M] ダウンロード画質: 360p (HEVC)
[M] 少年Pi - pi,mc,恐锤P1_x264
[M] hev1: 100%|██████████| 90.9M/90.9M [00:07<00:00, 12.8MB/s]
[M] mp4a: 100%|██████████| 38.1M/38.1M [00:02<00:00, 12.8MB/s]
[M] ファイルを変換中...
[M] 5秒待機中...
[M] ダウンロード画質: 360p (AVC)
[M] 少年Pi - pi,mc,恐锤P2_x264
[M] avc1: 100%|██████████| 90.6M/90.6M [00:01<00:00, 81.9MB/s]
[M] mp4a: 100%|██████████| 33.3M/33.3M [00:00<00:00, 83.7MB/s]
[M] ファイルを変換中...
[M] 5秒待機中...
###--------------------------------------###

**Comment by strd3983** [comment]
ありがとうございます。
大丈夫そうですね。
この後正式にリリースしてissue閉じます👍
